=== andre0xFF/ISEL-LEIM-ICD/Projects/P01/references/peça.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Porfírio Filipe -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Peça">
		<xs:annotation>
			<xs:documentation>Peça de Equipamento Desportivo</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Foto" type="xs:anyURI" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Caminho para ficheiros com imagens ilustrativas</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Descrição">
					<xs:annotation>
						<xs:documentation>Descrição</xs:documentation>
					</xs:annotation>
					<xs:complexType mixed="true">
						<xs:all>
							<xs:element name="Carateristica" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Carateristica referida na descrição da peça</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:choice>
					<xs:element name="Vestuário">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Tamanho" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="Valor" use="required">
											<xs:annotation>
												<xs:documentation>Referencia o tamanho</xs:documentation>
											</xs:annotation>
										</xs:attribute>
										<xs:attribute name="Quantidade" type="xs:unsignedInt" use="required">
											<xs:annotation>
												<xs:documentation>Quantidade em stock relativa ao tamanho indicado</xs:documentation>
											</xs:annotation>
										</xs:attribute>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Calçado">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Tamanho" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="Valor" type="xs:byte" use="required">
											<xs:annotation>
												<xs:documentation>Referencia o tamanho</xs:documentation>
											</xs:annotation>
										</xs:attribute>
										<xs:attribute name="Quantidade" type="xs:unsignedInt" use="required">
											<xs:annotation>
												<xs:documentation>Quantidade em stock relativa ao tamanho indicado</xs:documentation>
											</xs:annotation>
										</xs:attribute>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="idPeça" use="required">
				<xs:annotation>
					<xs:documentation>Código Único</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Designação" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Designação Comercial</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Secção" use="required">
				<xs:annotation>
					<xs:documentation>Secção da Loja. Homem. Senhora, Criança</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Criança"/>
						<xs:enumeration value="Senhora"/>
						<xs:enumeration value="Homem"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Marca" type="xs:base64Binary" use="required">
				<xs:annotation>
					<xs:documentation>Contém o logotipo da marca em base64</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Preço" use="required">
				<xs:annotation>
					<xs:documentation>Preço em Euros</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="0"/>
						<xs:fractionDigits value="2"/>
						<xs:totalDigits value="8"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
		<xs:key name="pkPeça">
			<xs:selector xpath="."/>
			<xs:field xpath="@idPeça"/>
		</xs:key>
		<xs:unique name="akCalçado">
			<xs:selector xpath="Calçado/Tamanho"/>
			<xs:field xpath="@Valor"/>
		</xs:unique>
		<xs:key name="akVestuário">
			<xs:selector xpath="Vestuário/Tamanho"/>
			<xs:field xpath="@Valor"/>
		</xs:key>
	</xs:element>
</xs:schema>

=== andre0xFF/ISEL-LEIM-ICD/Projects/P01/references/palmilha/palmilha.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Peça Marca="UjBsR09EbGhjZ0dTQUxNQUFBUUNBRU1tQ1p0dU1GUXhEUzhi" Secção="Homem" Preço="25.00" idPeça="1" Designação="PALMILHA DE AMORTECIMENTO FULL STRIKE" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../peça.xsd">
	<Foto>f1.jpg</Foto>
	<Foto>f2.jpg</Foto>
	<Descrição>Para o praticante de corrida que necessita de <Carateristica>amortecimento</Carateristica>
	</Descrição>
	<Calçado>
		<Tamanho Quantidade="1" Valor="42"/>
		<Tamanho Quantidade="3" Valor="43"/>
	</Calçado>
</Peça>
