=== andre0xFF/ISEL-LEIM-ICD/x/Examples/aula3/WebContent/xml/poema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- P. Filipe -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="T_Nome">
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z|аюцбихмлрсутыз][a-z|АЮЦБИХМЛСРУТЗЫГ]{1,30}|((\s(d'|((du|da|de|do|dos)\s))?)[A-Z|аюцбихмлрсутыз][a-z|АЮЦБИХМЛСРУТЗЫГ]{1,30}))+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="T_poema">
		<xs:sequence>
			<xs:element ref="autor"/>
			<xs:element ref="titulo"/>
			<xs:element name="estrofe" minOccurs="1" maxOccurs="15">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="verso" type="xs:string" minOccurs="1" maxOccurs="15"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="titulo" type="xs:string"/>
	<xs:element name="poema" type="T_poema"/>
	<xs:element name="autor" type="T_Nome"/>
</xs:schema>

=== andre0xFF/ISEL-LEIM-ICD/x/Examples/aula3/WebContent/poemas/Os Lusíadas (Quarto Canto).xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<poema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="poema.xsd">
	<autor>Luís de Camões</autor>
	<titulo>Os Lusíadas (quarto canto)</titulo>
	<estrofe>
		<verso>DESPOIS de procelosa tempestade,</verso>
		<verso>Nocturna sombra e sibilante vento,</verso>
		<verso>Traz a manha serena claridade,</verso>
		<verso>Esperança de porto e salvamento;</verso>
		<verso>Aparta o Sol a negra escuridade,</verso>
		<verso>Removendo o temor ao pensamento:</verso>
		<verso>Assi no Reino forte aconteceu</verso>
		<verso>Despois que o Rei Fernando faleceu.</verso>
	</estrofe>
	<estrofe>
		<verso>Porque, se muito os nossos desejaram</verso>
		<verso>Quem os danos e ofensas vão vingando</verso>
		<verso>Naqueles que tão bem se aproveitaram</verso>
		<verso>Do descuido remisso de Fernando,</verso>
		<verso>Despois de pouco tempo o alcançaram,</verso>
		<verso>Joane, sempre ilustre, alevantando</verso>
		<verso>Por Rei, como de Pedro único herdeiro</verso>
		<verso>(Ainda que bastardo) verdadeiro.</verso>
	</estrofe>
	<estrofe>
		<verso>Ser isto ordenação dos Céus divina</verso>
		<verso>Por sinais muito claros se mostrou,</verso>
		<verso>Quando em Évora a voz de ua minina,</verso>
		<verso>Ante tempo falando, o nomeou.</verso>
		<verso>E, como cousa, enfim, que o Céu destina,</verso>
		<verso>No berço o corpo e a voz alevantou:</verso>
		<verso>-«Portugal, Portugal (alçando a mão,</verso>
		<verso>Disse) polo Rei novo, Dom João!»</verso>
	</estrofe>
</poema>

=== andre0xFF/ISEL-LEIM-ICD/x/Examples/aula3/WebContent/poemas/Os Colombos.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<poema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="poema.xsd">
	<autor>Fernando Pessoa</autor>
	<titulo>Os Colombos</titulo>
	<estrofe>
		<verso>Outros haverão de ter</verso>
		<verso>O que houvermos de perder.</verso>
		<verso>Outros poderão achar</verso>
		<verso>O que, no nosso encontrar,</verso>
		<verso>Foi achado, ou não achado,</verso>
		<verso>Segundo o destino dado.</verso>
	</estrofe>
	<estrofe>
		<verso>Mas o que a eles não toca</verso>
		<verso>É a Magia que evoca</verso>
		<verso>O Longe e faz dele história.</verso>
		<verso>E por isso a sua glória</verso>
		<verso>É justa auréola dada</verso>
		<verso>Por uma luz emprestada.</verso>
	</estrofe>
</poema>

=== andre0xFF/ISEL-LEIM-ICD/x/Examples/aula3/WebContent/poemas/Invictus.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<poema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="poema.xsd">
	<autor>William Ernest Henley</autor>
    <titulo>Invictus</titulo>	
	<estrofe>
		<verso>Out of the night that covers me,</verso>
		<verso>Black as the Pit from pole to pole,</verso>
		<verso>I thank whatever gods may be</verso>
		<verso>For my unconquerable soul.</verso>
	</estrofe>
	<estrofe>
		<verso>In the fell clutch of circumstance</verso>
		<verso>I have not winced nor cried aloud.</verso>
		<verso>Under the bludgeonings of chance</verso>
		<verso>My head is bloody, but unbowed.</verso>
	</estrofe>
	<estrofe>
		<verso>Beyond this place of wrath and tears</verso>
		<verso>Looms but the Horror of the shade,</verso>
		<verso>And yet the menace of the years</verso>
		<verso>Finds, and shall find, me unafraid.</verso>
	</estrofe>
	<estrofe>
		<verso>It matters not how strait the gate,</verso>
		<verso>How charged with punishments the scroll,</verso>
		<verso>I am the master of my fate:</verso>
		<verso>I am the captain of my soul.</verso>
	</estrofe>
</poema>

=== andre0xFF/ISEL-LEIM-ICD/x/Examples/aula3/WebContent/poemas/O dialogo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<poema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="poema.xsd">
	<autor>Bando dos Quatro</autor>
    	<titulo>O dialogo</titulo>
	<estrofe>
		<verso>O stor tava a filmar</verso>
		<verso>e eu tou com vontade de ir fumar</verso>
		<verso>e as quatro vou bazar</verso>
		<verso>pensando melhor acho que vou arrancar</verso>
	</estrofe>
	<estrofe>
		<verso>Nao sei o que fazer</verso>
		<verso>nem sei o que estou a ler</verso>
		<verso>o xml nao abre</verso>
		<verso>vou ter que o reescrever</verso>
	</estrofe>
	<estrofe>
		<verso>Estamos aqui em IECD</verso>
		<verso>a escrever um poema que nao se lê</verso>
		<verso>amanha é quinta feira</verso>
		<verso>e vou apanhar uma bubadeira</verso>
	</estrofe>
	<estrofe>
		<verso>O Gonçalo tem pastilha na prata</verso>
		<verso>e ele esta com uma dama que nao lhe tira a pata</verso>
		<verso>rata</verso>
	</estrofe>
	<estrofe>
		<verso>Deixa-mos aqui escrito este poema</verso>
		<verso>em prolo de um grande dilema</verso>
		<verso>sabemos que IASA vai dar problema</verso>
		<verso>mas até à quinta semana</verso>
		<verso>nao há drena</verso>
	</estrofe>
</poema>

=== andre0xFF/ISEL-LEIM-ICD/x/Examples/aula3/WebContent/poemas/Mar Português.xml
<?xml version="1.0" encoding="UTF-8"?>
<poema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="poema.xsd">
	<autor>Fernando Pessoa</autor>
	<titulo>Mar Português</titulo>
	<estrofe>
		<verso>Ó mar salgado, quanto do teu sal</verso>
		<verso>São lágrimas de Portugal!</verso>
		<verso>Por te cruzarmos, quantas mães choraram,</verso>
		<verso>Quantos filhos em vão rezaram!</verso>
		<verso>Quantas noivas ficaram por casar</verso>
		<verso>Para que fosses nosso, ó mar!</verso>
	</estrofe>
	<estrofe>
		<verso>Valeu a pena? Tudo vale a pena</verso>
		<verso>Se a alma não é pequena.</verso>
		<verso>Quem quer passar além do Bojador</verso>
		<verso>Tem que passar além da dor.</verso>
		<verso>Deus ao mar o perigo e o abismo deu,</verso>
		<verso>Mas nele é que espelhou o céu.</verso>
	</estrofe>
</poema>

=== andre0xFF/ISEL-LEIM-ICD/x/Examples/aula3/WebContent/poemas/comboio Descendente.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<poema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="poema.xsd">
<autor>Fernando Pessoa</autor>
<titulo>Comboio Descendente</titulo>
<estrofe>
<verso>No comboio descendente</verso>
<verso>Vinha tudo à gargalhada,</verso>
<verso>Uns por verem rir os outros</verso>
<verso>E os outros sem ser por nada </verso>
<verso>No comboio descendente</verso>
<verso>De Queluz à Cruz Quebrada...</verso>
</estrofe>
<estrofe>
<verso>No comboio descendente</verso>
<verso>Vinham todos à janela,</verso>
<verso>Uns calados para os outros</verso>
<verso>E os outros a dar-lhes trela </verso>
<verso>No comboio descendente</verso>
<verso>Da Cruz Quebrada a Palmela...</verso>
</estrofe>
<estrofe>
<verso>No comboio descendente</verso>
<verso>Mas que grande reinação!</verso>
<verso>Uns dormindo, outros com sono,</verso>
<verso>E os outros nem sim nem não </verso>
<verso>No comboio descendente</verso>
<verso>De Palmela a Portimão...</verso>
</estrofe>
</poema>
